const STORAGE_KEY="ausbildungsEintraege";
let entries=JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");
let recognition=null,isListening=false,deleteId=null;
let calendarDate=new Date(),selectedDate=null;
const $=id=>document.getElementById(id);
function escapeHtml(value=""){return String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
function saveEntries(){localStorage.setItem(STORAGE_KEY,JSON.stringify(entries));}
function localDate(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return `${y}-${m}-${day}`;}
function formatDate(date){return new Date(date+"T00:00:00").toLocaleDateString("de-DE",{weekday:"short",day:"2-digit",month:"2-digit",year:"numeric"});}
function renderEntries(list=entries){const c=$("entriesList");if(!list.length){c.innerHTML='<div class="empty">Noch keine passenden Einträge. ✍️</div>';}else{const sorted=[...list].sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id);c.innerHTML=sorted.map(e=>`<article class="entry-card ${e.important?"important":""}"><div class="entry-top"><span class="badge">${escapeHtml(e.category)}</span><span class="date">${formatDate(e.date)}</span></div><h3>${escapeHtml(e.title)}</h3><p>${escapeHtml(e.description)}</p>${e.learned?`<p class="learned"><strong>Gelernt:</strong> ${escapeHtml(e.learned)}</p>`:""}<div class="entry-actions"><button type="button" data-action="important" data-id="${e.id}">${e.important?"⭐ Wichtig":"☆ Wichtig"}</button><button type="button" class="delete-button" data-action="delete" data-id="${e.id}">🗑️ Löschen</button></div></article>`).join("");}$("entryCount").textContent=`${list.length} ${list.length===1?"Eintrag":"Einträge"}`;}
function applyFilters(){const q=$("searchInput").value.toLowerCase().trim(),cat=$("categoryFilter").value;let filtered=entries.filter(e=>{const hay=`${e.title} ${e.description} ${e.learned} ${e.category}`.toLowerCase();return(!q||hay.includes(q))&&(!cat||e.category===cat);});if(selectedDate)filtered=filtered.filter(e=>e.date===selectedDate);renderEntries(filtered);}
function openModal(transcript=""){ $("entryModal").classList.remove("hidden");$("description").value=transcript;$("title").value=transcript?transcript.split(/\s+/).slice(0,6).join(" ").replace(/[.!?]$/," ").trim():"";$("today").value=selectedDate||localDate();$("title").focus();}
function closeModal(){$("entryModal").classList.add("hidden");$("entryForm").reset();$("today").value=selectedDate||localDate();}
function setupSpeech(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return;recognition=new SR();recognition.lang="de-DE";recognition.continuous=false;recognition.interimResults=false;recognition.onstart=()=>{isListening=true;$("voiceButton").textContent="⏹️ Aufnahme stoppen";$("voiceButton").classList.add("listening")};recognition.onend=()=>{isListening=false;$("voiceButton").textContent="🎤 Eintrag sprechen";$("voiceButton").classList.remove("listening")};recognition.onerror=e=>{if(e.error==="not-allowed"||e.error==="service-not-allowed")alert("Mikrofonzugriff wurde nicht erlaubt.");else if(e.error==="no-speech")alert("Ich habe nichts verstanden. Versuch es bitte noch einmal.");else alert("Die Spracheingabe konnte nicht gestartet werden.")};recognition.onresult=e=>openModal(e.results[0][0].transcript.trim());}
function startSpeech(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert("Dein Browser unterstützt diese Spracheingabe nicht.");return;}if(!recognition)setupSpeech();try{isListening?recognition.stop():recognition.start()}catch(_){} }
function renderCalendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth();$("monthTitle").textContent=calendarDate.toLocaleDateString("de-DE",{month:"long",year:"numeric"});const first=new Date(y,m,1),start=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),prevDays=new Date(y,m,0).getDate();let html=["Mo","Di","Mi","Do","Fr","Sa","So"].map(x=>`<div class="weekday">${x}</div>`).join("");for(let i=0;i<42;i++){let n=i-start+1,day=n,mm=m,yy=y,muted=false;if(n<1){day=prevDays+n;mm=m-1;muted=true}if(n>days){day=n-days;mm=m+1;muted=true}const d=new Date(yy,mm,day),key=localDate(d),has=entries.some(e=>e.date===key),today=key===localDate(),sel=key===selectedDate;html+=`<button type="button" class="day ${muted?"muted":""} ${today?"today":""} ${has?"has-entry":""} ${sel?"selected":""}" data-date="${key}">${day}</button>`;}$("calendar").innerHTML=html;$("calendar").querySelectorAll(".day").forEach(b=>b.addEventListener("click",()=>{selectedDate=b.dataset.date;$("selectedDateLabel").textContent=`Einträge für ${formatDate(selectedDate)}`;renderCalendar();applyFilters();}));}
function clearDate(){selectedDate=null;$("selectedDateLabel").textContent="Alle Einträge";renderCalendar();applyFilters();}
function init(){ $("today").value=localDate();$("voiceButton").addEventListener("click",startSpeech);$("manualButton").addEventListener("click",()=>openModal());$("closeModal").addEventListener("click",closeModal);$("cancelButton").addEventListener("click",closeModal);$("entryForm").addEventListener("submit",e=>{e.preventDefault();const entry={id:Date.now(),title:$("title").value.trim()||"Ohne Titel",description:$("description").value.trim(),learned:$("learned").value.trim(),category:$("category").value,date:$("today").value,important:$("important").checked};if(!entry.description){alert("Bitte gib eine Beschreibung ein.");return;}entries.push(entry);saveEntries();closeModal();renderCalendar();applyFilters();});$("searchInput").addEventListener("input",applyFilters);$("categoryFilter").addEventListener("change",applyFilters);$("clearSearch").addEventListener("click",()=>{$("searchInput").value="";$("categoryFilter").value="";clearDate();});$("entriesList").addEventListener("click",e=>{const b=e.target.closest("button[data-action]");if(!b)return;const id=Number(b.dataset.id);if(b.dataset.action==="delete"){deleteId=id;$("confirmModal").classList.remove("hidden");return;}entries=entries.map(x=>x.id===id?{...x,important:!x.important}:x);saveEntries();applyFilters();renderCalendar();});$("confirmDelete").addEventListener("click",()=>{if(deleteId!==null){entries=entries.filter(x=>x.id!==deleteId);saveEntries();deleteId=null;$("confirmModal").classList.add("hidden");applyFilters();renderCalendar();}});$("cancelDelete").addEventListener("click",()=>{$("confirmModal").classList.add("hidden");deleteId=null});$("prevMonth").addEventListener("click",()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar()});$("nextMonth").addEventListener("click",()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar()});$("todayButton").addEventListener("click",()=>{calendarDate=new Date();selectedDate=localDate();$("selectedDateLabel").textContent=`Einträge für ${formatDate(selectedDate)}`;renderCalendar();applyFilters()});$("bottom");document.querySelectorAll(".bottom button").forEach(b=>b.addEventListener("click",()=>{const n=b.dataset.nav;if(n==="calendar")document.querySelector(".calendar-section").scrollIntoView({behavior:"smooth"});if(n==="search"){$("searchInput").focus();document.querySelector(".tools").scrollIntoView({behavior:"smooth"});}if(n==="home")window.scrollTo({top:0,behavior:"smooth"});}));renderCalendar();$("selectedDateLabel").textContent="Alle Einträge";renderEntries();setupSpeech();}
document.addEventListener("DOMContentLoaded",init);
